import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillLinkedin, AiFillInstagram } from 'react-icons/ai';
import { Image } from 'next/image';
import { FotoPerfil } from '../public/mgdistribuciones.png';



export default function Home() {
  return (
    <div>
      <Head>
        <title>Alex M</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className=' bg-white px-10'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-end'>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill className='cursor-pointer text-2xl'/></li>
              <li><a href="#" className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'>Mi CV</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>Alex Mendoza</h2>
            <h3 className='text-2xl py-2'>React Developer</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor, aspernatur! 
              Tenetur cumque neque nostrum itaque est sed? Quaerat aut, 
              molestias eligendi facere in fuga repellendus corrupti omnis impedit sunt beatae.</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3'>
            <AiFillLinkedin />
            <AiFillInstagram />
          </div>
          <div className='relative'>
            <Image src={ FotoPerfil } />
          </div>
        </section>
      </main>

    </div>
  )
}
